comment: false

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    patch: no
    project:
      default: no
      reactioncommerce-api-client:
        flags: reactioncommerce-api-client
        target: 90%
      reactioncommerce-composables:
        flags: reactioncommerce-composables
        target: 90%
flags:
  reactioncommerce-api-client:
    paths:
      - packages/reactioncommerce/api-client
  reactioncommerce-composables:
    paths:
      - packages/reactioncommerce/composables
