name: Release
on: workflow_dispatch

jobs:
  release_stable:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Releasing...
        uses: actions/github-script@v4
        id: set-next-ver
        with:
          script: |
            const { version } = require('./lerna.json');
            const ver = version.replace(
              /(\d+)\.(\d+)\.(\d+)/, (_, a, b, c) => a + '-' + (parseInt(b) + 1)
            );

            return `release-${ver}`
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${{steps.set-next-ver.outputs.result}}
          git push origin ${{steps.set-next-ver.outputs.result}}
          yarn release-stable --yes
          git checkout master
          git merge ${{steps.set-next-ver.outputs.result}}
          git commit
          git push origin master
          

  release_patch:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'release-')
    steps:
    - run: |
        echo "test workflow release"